redpitaya:
  hostname: 10.214.1.9
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  gui: true
  monitor_server_name: monitor_server
general:
  name: cavity_membrane
  loglevel: debug
  curvedb: pyinstruments
model:
  modeltype: fpm
  wavelength: 1.064e-06
  maxerror: 0.1
inputs:
  transmission:
    redpitaya_input: adc1
  reflection:
    redpitaya_input: adc2
outputs:
  slow:
    unity_gain_frequency: 1000.0
    redpitaya_output: out2
    max_voltage: 0.8
    min_voltage: -0.8
    m_per_V: 500e-9
    analogfilter:
      lowpass:
      - 50
    inputfilter:
    - 0
    - 0
    - 0
    - 0
    calibrationunits: m_per_V
    sweep:
      waveform: sin
      frequency: 25.0
      amplitude: 0.8
  piezo:
    redpitaya_output: out1
    calibrationunits: m_per_V
    m_per_V: 10e-09
    analogfilter:
      lowpass: []
    inputfilter:
    - 9714.04681957369
    - 0
    - 0
    - 0
    unity_gain_frequency: 1000.0
    max_voltage: 0.9998779296875
    min_voltage: -1.0
scope:
  input1: adc2
  input2: dac2
  duration: 0.1
  trigger_source: immediately
  average: false
signal:
  unit: V
  V_per_V: 1.0
  raw_per_V: 8192.0
  duration: 0.1
  average: false
  autosave: true
  points: 16384
  trigger_source: immediately
  acquire_timeout: 0.5
  offset_subtraction: true
  offset: 0
  peak: 0
