model:
  type: fabry-perot
  cavity:
    length: 0.5
    finesse: 5000
    actuator:
      type: pzt
      lowpass: 10.0
      gain: 5555
      iir:
        value: 2.4+1j #test 
        description: iir filter coefficients
        ro: false
general:
  hostname: 192.168.1.100
  user: toor
  password: toor

