redpitaya:
  hostname: 10.214.1.9
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  # autostart gui?
  gui: true
  monitor_server_name: monitor_server

general:
  # name of this device
  name: fpm
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  loglevel: debug
  # import CurveDB class from which module? if missing, it's pyrpl.curvedb
  #curvedb: pyrpl
  curvedb: pyinstruments

# most important section that defines how the lockbox understands the
# real-world system
model:
  # use class Interferometer for internal model and lock algorithms
  # upper- or lowercase spelling is accepted if there is no ambiguity
  modeltype: fabryperot_reflection
  # only needed parameter is wavelength
  # (to convert piezo displacement into gain)
  wavelength: 1.064e-06
  # maximum tolerated error of the internal variable
  # for interferometer, this is the phase error in radians
  # this value is uniquely needed for the function 'islocked'
  maxerror: 0.1

# all signals that are inputs of the lockbox. Must be signal names understood
# by the model
inputs:
  # the reflection photodiode
  reflection:
    redpitaya_input: adc2
  # the photodiode for the external pdh signal
  pdh:
    redpitaya_input: adc1

# All output signals. Names of outputs are arbitrary.
outputs:
  # the very coarse piezo. at the moment, it is controlled manually
  slow:
    redpitaya_output: pwm0
    max_voltage: 1.0
    min_voltage: -1.0
    # amplitier gain complicated - calibrate manually. at the moment
    m_per_V: 1.0
    analogfilter:
      # yes: there is a 10 mHz filter behind pwm output
      lowpass:
      - 0.01
  # we only have 1 actuator in this interferometer, the piezo in the LO arm
    inputfilter:
    - 0
    - 0
    - 0
    - 0
    calibrationunits: m_per_V
  piezo:
    redpitaya_output: out2
    # we will calibrate the piezo response in units of m_per_V (not a necessary
    # parameter as it can be automatically filled in by the code)
    calibrationunits: m_per_V
    # piezo: PD080.31
    # piezo specification: 2 micron / 100 V
    # cryogenic penalty factor: 6
    # piezo amplifier gain: 1 V / V
    # therefore effective DC gain of piezo:
    # 3.1 nm / V
    # light is reflected from this mirror at 45 degrees
    # this decreases the effective displacement by a factor of sqrt(2) to 1.77
    m_per_V: 3.1e-09
    # PZT parallel capacity: 1 uF
    # Series resistance: 50 Ohm + 10 kOhm
    # RC cutoff 1/2piRC = 37.9 Hz
    # therefore the analog filter can be well approximated by a first order
    # lowpass with corner frequency 37.9 Hz
    analogfilter:
      lowpass:
      - 15.8
    # the piezo manufacturer specifies the first resonance at 144 kHz
    # however, the mounting structure is expected to have resonances starting
    # from 15 kHz. To be safe, we start by demanding a unity-gain frequency
    # of 1 kHz and will later increase this value (automatically done after
    # lock optimisation)
    unity_gain_frequency: 1000.0
    inputfilter:
    - 4857.023409786845
    - 4857.023409786845
    - 4857.023409786845
    - 4857.023409786845
    sweep:
      waveform: sin
      frequency: 25.0
      amplitude: 0.85

    max_voltage: 0.9998779296875
    min_voltage: -1.0
##############################################################################
###  Configuration parameters that rarely need to be modified ################
##############################################################################

scope:
  input1: adc2
  input2: dac2
  duration: 0.1
  trigger_source: immediately
  average: false

# default properties for signal acquisition
signal:
  unit: V # can be any of m, Hz, V, raw, ... as long as unit_per_V is defined
  V_per_V: 1.0 # default unit is V
  raw_per_V: 8192.0 # raw units from the FPGA
  # minimum trace duration in seconds
  # be aware that this number affects both the sampling rate and the minimum
  # frequency that can be resolved. Usually, you want to keep duration as long
  # as you can stand to wait for new signal data, typically 10-100 ms.
  duration: 0.1
  # selects whether scope is to be used in average mode
  # false is strongly suggested for duration-independent estimation of rms
  # true is preferred only when we want to get an extremely good mean estimate
  average: false
  # if true, the signal.curve command automatically saves the data to CurveDB
  autosave: true
  # number of points per curve; also the number of points used for mean and rms
  points: 16384
  # default trigger source
  trigger_source: immediately
  # timeout determines the time interval within which we do not take another
  # data trace if several parameters are requested. To always obtain fresh
  # data, set this to -1. To enable manual acquisition control with the acquire
  # function '_acquire()', set this to a very large value or to '.inf'.
  timeout: 0.5
  # if true, the offset is subtraced. Calibrate with signal.get_offset()
  offset_subtraction: true
  offset: 0
  # peak is a reserved place to store the peak value, for example offresonant
  # reflection from a cavity
  peak: 0

