pyrpl:
  name: test_refactor
  gui: true
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAVWAAACnfwBAAAAAfwAAAAAAAAFVgAAA/EA////+gAAAAMBAAAA
    B/sAAAAIAGEAcwBnAHMAAAAAAP////8AAAAUAP////sAAAAGAGkAcQBzAAAAAAD/////AAAAFAD/
    ///7AAAACABwAGkAZABzAAAAAAD/////AAAAFAD////7AAAADABzAGMAbwBwAGUAcwEAAAAA////
    /wAAA/EA////+wAAAAgAaQBpAHIAcwAAAAAA/////wAAABQA////+wAAAAQAbgBhAAAAAAD/////
    AAAAFAD////7AAAAIgBzAHAAZQBjAHQAcgB1AG0AXwBhAG4AYQBsAHkAegBlAHIAAAAAAP////8A
    AAMKAP///wAABVYAAAAAAAAABAAAAAQAAAAIAAAACPwAAAAA
  window_position:
  - -4
  - -4
  - 1366
  - 705
redpitaya:
  hostname: 192.168.1.107
  user: root
  password: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
nas:
  na: {}
spectrum_analyzers:
  spectrum_analyzer:
    input: adc2
hks:
  hk: {}
amss:
  ams: {}
scopes:
  scope:
    trigger_source: immediately
    input1: adc1
    input2: adc2
    running_continuous: false
    duration: 8.589934592
    rolling_mode: true
    average: false
samplers:
  sampler: {}
asgs:
  asg1: {}
  asg2: {}
pwms:
  pwm1: {}
  pwm2: {}
iqs:
  iq1: {}
pids:
  pid1: {}
  pid2: {}
  pid3: {}
  pid4: {}
iirs:
  iir: {}
