redpitaya:
  hostname: 10.214.1.29
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
  gui: true
general:
  name: membrane
  loglevel: info
  curvedb: pyinstruments
model:
  modeltype: FPMembranes
  wavelength: 1.064e-06
  finesse: 4500.0
  length: 0.015
  lock:
    error_threshold: 1.0
    stages:
      drift:
        input: transmission
        outputs:
        - piezo
        detuning: 2
        factor: 0.5
        time: 3.0
        offset: 0.8
      pdh_piezo:
        input: pdh
        outputs:
        - piezo
        detuning: 0
        factor: 0.1
        time: 3.0
      pdh:
        input: pdh
        detuning: 0
        factor: 1
  calibrate:
    zoomfactor: 0.01
    relative_threshold: 0.7
  resonant_reflection: 0.0546875
  offresonant_reflection: 0.217529296875
  resonant_transmission: 0.17600759863853455
  peak_pdh: 0.29962158203125
inputs:
  transmission:
    redpitaya_input: adc1
    max: 0.17600759863853455
    min: -0.001970916986465454
    mean: 0.01068972796201706
    rms: 0.007263650621441482
    offset: -0.021466583013534546
    curve: 223475
  pdh:
    setup:
      input: adc2
      phase: 180.0
      amplitude: 0.2
      output_direct: out2
      frequency: 50000000.0
      gain: 0
      output_signal: quadrature
      quadrature_factor: 0.1
      bandwidth:
      - 500000.0
      - 500000.0
      acbandwidth: 100000.0
    redpitaya_input: iq0
    max: 0.2969970703125
    min: -0.30224609375
    mean: -0.004274927079677582
    rms: 0.044262766453291746
    curve: 223477
outputs:
  piezo:
    redpitaya_output: out2
    max_voltage: 0.8
    min_voltage: -0.8
    Hz_per_V: 1792572653.8004928
    analogfilter:
      lowpass:
      - 50
    sweep:
      waveform: ramp
      frequency: 25.0
      amplitude: 0.8
    lock:
      unity_gain_frequency: 500.0
      inputfilter:
      - 0
      - 0
      - 0
      - 0
    calibrationunits: Hz_per_V
  current:
    redpitaya_output: out1
    max_voltage: 1.0
    min_voltage: -1.0
    Hz_per_V: 20000000000.0
    lock:
      proportional_gain: 500
      inputfilter:
      - 0
      - 0
      - 0
      - 0
    analogfilter:
      lowpass:
      - 10000
    calibrationunits: Hz_per_V
scope:
  average: true
  duration: 0.067108864
  input1: adc1
  input2: dac2
  trigger_delay: 0.033554432
  trigger_source: immediately
scopegui:
  coordinates:
  - 0
  - 0
  - 1689
  - 972
  auto_run_continuous: true
signal:
  unit: V
  V_per_V: 1.0
  raw_per_V: 8192.0
  duration: 0.1
  average: false
  autosave: true
  points: 16384
  trigger_source: immediately
  threshold: 0
  hysteresis: 0.002
  acquire_timeout: 0.5
  offset_subtraction: true
  offset: 0
  peak: 0
  trigger_delay: 0
dock_positions: !!binary |
  AAAA/wAAAAD9AAAAAQAAAAIAAAaZAAADzPwBAAAAAfwAAAAAAAAGmQAABb8A/////AIAAAAD/AAA
  AAAAAAIuAAAAAAD////6AAAAAAEAAAAD+wAAAAoAcwBjAG8AcABlAQAAAAD/////AAAAAAAAAAD7
  AAAABABuAGEBAAAAAP////8AAAAAAAAAAPsAAAAEAHMAYQEAAAAA/////wAAAAAAAAAA/AAAAAAA
  AACqAAAAAAD////8AQAAAAH7AAAACABhAHMAZwBzAQAAAAAAAALqAAAAAAAAAAD8AAAAAAAAA8wA
  AAIuAP////wBAAAAAvwAAAAAAAADHwAAAkUA/////AIAAAAF+wAAABoAUAB5AHIAcABsACAAYwBv
  AG4AdAByAG8AbAEAAAAAAAAAbgAAAG4A////+wAAACAATABpAHYAZQAgAGYAaQB0ACAAZgBpAG4A
  ZQBzAHMAZQEAAAByAAAAWgAAAFoA/////AAAAXYAAADQAAAAAAD////6AAAAAAIAAAAC+wAAACAA
  TABpAHYAZQBfAGYAaQB0AF8AZgBpAG4AZQBzAHMAZQEAAAAA/////wAAAAAAAAAA+wAAABQATQBv
  AHQAbwByACAAUwBjAGEAbgEAAAAA/////wAAAAAAAAAA+wAAAAgAQQBzAGcAcwEAAADQAAACKAAA
  AIoA////+wAAABQATQBvAHQAbwByACAAcwBjAGEAbgEAAAL8AAAA0AAAANAA/////AAAAyMAAAN2
  AAADdgD////8AgAAAAL7AAAAIABMAGkAdgBlACAARgBpAHQAIABGAGkAbgBlAHMAcwBlAQAAAAAA
  AACGAAAAAAAAAAD8AAAAAAAAA8wAAAEBAQAAFPoAAAABAQAAAAL7AAAABABOAGEBAAAAAP////8A
  AAN2AP////sAAAAeAFMAYwBvAHAAZQAvAFMAcABlAGMALgAgAEEAbgAuAQAAAxoAAAN2AAADcwD/
  //8AAAaZAAAAAAAAAAQAAAAEAAAACAAAAAj8AAAAAA==
Live fit finesse:
  length: 0.0157
  mod_freq: 50000000.0
Motor scan:
  lambda_start: 1055.0
  lambda_stop: 1075.0
  threshold: 0.05
