redpitaya:
  hostname: 10.214.1.29
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
  gui: true
general:
  name: membrane
  loglevel: info
  curvedb: pyinstruments
model:
  modeltype: FPMembranes
  wavelength: 1.064e-06
  finesse: 4500.0
  length: 0.015
  lock:
    error_threshold: 1.0
    stages:
      drift:
        input: transmission
        outputs:
        - piezo_direct
        detuning: 1
        factor: 0.1
        time: 3
        offset: -0.6
      pdh:
        input: pdh
        outputs:
        - piezo_direct
        - current
        detuning: 0
        factor: 1
  calibrate:
    zoomfactor: 0.01
    relative_threshold: 0.7
  resonant_reflection: 0.0546875
  offresonant_reflection: 0.217529296875
  resonant_transmission: 0.19407400488853455
  peak_pdh: 0.99993896484375
inputs:
  transmission:
    redpitaya_input: adc1
    max: 0.14
    min: -0.001482635736465454
    mean: 0.009311310946941376
    rms: 0.0028937231198821645
    offset: -0.021466583013534546
    curve: 224571
  pdh:
    setup:
      input: adc2
      phase: 180.0
      amplitude: 0.1
      output_direct: out2
      frequency: 50000000.0
      gain: 0
      output_signal: quadrature
      quadrature_factor: 0.05
      bandwidth:
      - 5000000.0
      - 5000000.0
      acbandwidth: 100000.0
    redpitaya_input: iq0
    max: 0.95
    min: -0.95
    mean: 0.003125429153442383
    rms: 0.017316065187902362
    curve: 224573
outputs:
  piezo_pwm:
    redpitaya_output: pwm0
    max_voltage: 1
    min_voltage: -1
    Hz_per_V: 14285714285
    analogfilter:
      lowpass:
      - 50
    sweep:
      waveform: ramp
      frequency: 25.0
      amplitude: 1
    lock:
      unity_gain_frequency: 1
      inputfilter:
      - 1214.2558524467113
      - 1214.2558524467113
      - 1214.2558524467113
      - 1214.2558524467113
    calibrationunits: Hz_per_V
  piezo_direct:
    redpitaya_output: out2
    max_voltage: 0.8
    min_voltage: -0.8
    Hz_per_V: -666666666
    analogfilter:
      lowpass:
      - 400
    sweep:
      waveform: ramp
      frequency: 25
      amplitude: 1
    lock:
      unity_gain_frequency: 10000
      inputfilter:
      - 0
      - 0
      - 0
      - 0
    calibrationunits: Hz_per_V
  current:
    redpitaya_output: out1
    max_voltage: 1.0
    min_voltage: -1.0
    Hz_per_V: 285714285
    lock:
      proportional_gain: -12000.0
      inputfilter:
      - -9.486373847239932
      - 151.7819815558389
      - 0
      - 0
    sweep:
      waveform: ramp
      frequency: 25.0
      amplitude: 0
    analogfilter:
      lowpass:
      - 2000
    calibrationunits: Hz_per_V
scope:
  average: true
  duration: 0.067108864
  input1: adc1
  input2: dac2
  trigger_delay: 0.033554432
  trigger_source: immediately
scopegui:
  coordinates:
  - 320
  - 497
  - 1545
  - 1128
  auto_run_continuous: true
signal:
  unit: V
  V_per_V: 1.0
  raw_per_V: 8192.0
  duration: 0.1
  average: false
  autosave: true
  points: 16384
  trigger_source: immediately
  threshold: 0
  hysteresis: 0.002
  acquire_timeout: 0.5
  offset_subtraction: true
  offset: 0
  peak: 0
  trigger_delay: 0
dock_positions: b'\x00\x00\x00\xff\x00\x00\x00\x00\xfd\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x06\t\x00\x00\x04h\xfc\x01\x00\x00\x00\x02\xfc\x00\x00\x00\x00\x00\x00\x02w\x00\x00\x02w\x00\xff\xff\xff\xfc\x02\x00\x00\x00\x03\xfb\x00\x00\x00\x08\x00A\x00s\x00g\x00s\x01\x00\x00\x00\x00\x00\x00\x00\x90\x00\x00\x00\x90\x00\xff\xff\xff\xfb\x00\x00\x00\x08\x00P\x00i\x00d\x00s\x01\x00\x00\x00\x94\x00\x00\x02\x10\x00\x00\x02\x10\x00\xff\xff\xff\xfb\x00\x00\x00\x16\x00P\x00y\x00r\x00p\x00l\x00
  \x00m\x00o\x00d\x00e\x00l\x01\x00\x00\x02\xa8\x00\x00\x01\xc0\x00\x00\x00\xca\x00\xff\xff\xff\xfc\x00\x00\x02{\x00\x00\x03\x8e\x00\x00\x03\x8e\x00\xff\xff\xff\xfa\x00\x00\x00\x00\x01\x00\x00\x00\x02\xfb\x00\x00\x00\x1e\x00S\x00c\x00o\x00p\x00e\x00/\x00S\x00p\x00e\x00c\x00.\x00
  \x00A\x00n\x00.\x01\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x03\x7f\x00\xff\xff\xff\xfb\x00\x00\x00\x04\x00N\x00a\x01\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x03\x8e\x00\xff\xff\xff\x00\x00\x06\t\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x00\x08\x00\x00\x00\x08\xfc\x00\x00\x00\x00'
Live fit finesse:
  length: 0.0157
  mod_freq: 50000000.0
Motor scan:
  lambda_start: 1055.0
  lambda_stop: 1080.0
  threshold: 0.05
