pyrpl: # General configuration of the software:
  name: test_refactor
  gui: true # autostart gui
  loglevel: info
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  modules: # SoftwareModules to load (in addition to IqManager, AsgManager, PidManager, ScopeManager)
    - NetworkAnalyzer
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAeAAAAESPwBAAAAAvwAAAAAAAAD1AAAA4kA/////AIAAAAD+wAA
    AAgAYQBzAGcAcwEAAAAVAAAArwAAAJQA////+wAAAAYAaQBxAHMBAAAAyAAAAWgAAAFoAP////sA
    AAAIAHAAaQBkAHMBAAACNAAAAikAAAIYAP////wAAAPYAAADqAAAA6YA/////AIAAAAC+wAAAAgA
    aQBpAHIAcwEAAAAVAAABLQAAAS0A/////AAAAUYAAAMXAAABEwEAABT6AAAAAQIAAAAD+wAAAAwA
    cwBjAG8AcABlAHMBAAAAAP////8AAADXAP////sAAAAgAG4AZQB0AHcAbwByAGsAXwBhAG4AYQBs
    AHkAegBlAHIBAAAAAP////8AAAD+AP////sAAAAKAHMAYwBvAHAAZQEAAAAA/////wAAAAAAAAAA
    AAAHgAAAAAAAAAAEAAAABAAAAAgAAAAI/AAAAAA=
  window_position:
  - -8
  - -8
  - 1920
  - 1137
redpitaya:
  hostname: 10.214.1.28
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server


network_analyzer:
  stop: 10000.0
  points: 1001
  input: pid1
  infer_open_loop_tf: false
  rbw:
  - 4.0
  avg: 1
  start: 14.0
  output_direct: out1
  amplitude: 0.3
  logscale: true
  curve_name: na_c
asg1:
  output_direct: off
  waveform: sin
  trigger_source: immediately
  amplitude: 1.0
  offset: 0.0
  frequency: 0.0
asg2:
  offset: 0.0
  output_direct: off
  waveform: sin
  trigger_source: immediately
  frequency: 100799.95263367891
  amplitude: 0.2
scope:
  input1: asg2
  trigger_source: ch2_negative_edge
  threshold_ch1: 0.0
  trigger_delay: 0
  input2: iq1
  duration: '8.589934592'
  average: true
iq0:
  frequency: 100003.70384659618
  bandwidth:
  - 18.0
  - 18.0
  amplitude: 0.0
  quadrature_factor: 0.00390625
  phase: 10.00000351946801
  input: asg2
pid1:
  input: adc1
  inputfilter:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  output_direct: off
iq1:
  quadrature_factor: 0.001
  frequency: 100799.89151563495
  input: asg2
  bandwidth:
  - 151.0
  - 151.0
  gain: 0.0
  output_signal: quadrature
  output_direct: off
iq2:
  input: adc1
  bandwidth:
  - 0.0
  - 0.0
  output_signal: quadrature
  quadrature_factor: 1.0
  output_direct: off
pid2:
  inputfilter:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  input: adc2
  output_direct: off
pid3:
  inputfilter:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  input: adc1
  output_direct: off
pid4:
  inputfilter:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  input: adc2
  output_direct: off
