redpitaya:
  hostname: 10.214.1.29
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
  gui: true
general:
  name: membrane
  loglevel: info
  curvedb: pyinstruments
model:
  modeltype: FPMembranes
  wavelength: 1.064e-06
  finesse: 4500.0
  length: 0.015
  lock:
    error_threshold: 1.0
    stages:
      drift:
        input: transmission
        outputs:
        - piezo_direct #some comment
        detuning: 1
        factor: 0.1
        time: 3
        offset: 0.6
      pdh:
        input: pdh
        outputs:
        - piezo_direct
        - current
        detuning: 0
        factor: -5
  calibrate:
    zoomfactor: 0.01
    relative_threshold: 0.7
  resonant_reflection: 0.0546875
  offresonant_reflection: 0.217529296875
  resonant_transmission: 0.19407400488853455
  peak_pdh: 0.99993896484375
inputs:
  transmission:
    redpitaya_input: adc1
    max: 0.39
    min: -0.001482635736465454
    mean: 0.009311310946941376
    rms: 0.0028937231198821645
    offset: -0.021466583013534546
    curve: 224571
  pdh:
    setup:
      input: adc2
      phase: 180.0
      amplitude: 0.1
      output_direct: out2
      frequency: 50000000.0
      gain: 0
      output_signal: quadrature
      quadrature_factor: 0.1
      bandwidth:
      - 5000000.0
      - 5000000.0
      acbandwidth: 100000.0
    redpitaya_input: iq0
    max: 0.95
    min: -0.95
    mean: 0.003125429153442383
    rms: 0.017316065187902362
    curve: 224573
outputs:
  piezo_pwm:
    redpitaya_output: pwm0
    max_voltage: 1
    min_voltage: -1
    Hz_per_V: 14285714285
    analogfilter:
      lowpass:
      - 50
    sweep:
      waveform: ramp
      frequency: 25.0
      amplitude: 1
    lock:
      unity_gain_frequency: 1
      inputfilter:
      - 1214.2558524467113
      - 1214.2558524467113
      - 1214.2558524467113
      - 1214.2558524467113
    calibrationunits: Hz_per_V
  piezo_direct:
    redpitaya_output: out2
    max_voltage: 0.8
    min_voltage: -0.8
    Hz_per_V: 666666666
    analogfilter:
      lowpass:
      - 400
    sweep:
      waveform: ramp
      frequency: 25
      amplitude: 1
    lock:
      unity_gain_frequency: 500
      inputfilter:
      - 0
      - 0
      - 0
      - 0
    calibrationunits: Hz_per_V
  current:
    redpitaya_output: out1
    max_voltage: 1.0
    min_voltage: -1.0
    Hz_per_V: 285714285 #20000000000.0
    lock:
      proportional_gain: -40.0
      inputfilter:
      - -9.486373847239932
      - 0
      - 0
      - 0
    sweep:
      waveform: ramp
      frequency: 25.0
      amplitude: 0
    analogfilter:
      lowpass:
      - 2000
    calibrationunits: Hz_per_V
scope:
  average: true
  duration: 0.067108864
  input1: adc1
  input2: dac2
  trigger_delay: 0.033554432
  trigger_source: immediately
scopegui:
  coordinates:
  - -8
  - -8
  - 1680
  - 988
  auto_run_continuous: true
signal:
  unit: V
  V_per_V: 1.0
  raw_per_V: 8192.0
  duration: 0.1
  average: false
  autosave: true
  points: 16384
  trigger_source: immediately
  threshold: 0
  hysteresis: 0.002
  acquire_timeout: 0.5
  offset_subtraction: true
  offset: 0
  peak: 0
  trigger_delay: 0
dock_positions: !!binary |
  AAAA/wAAAAD9AAAAAQAAAAIAAAaQAAAD3PwBAAAAAfwAAAAAAAAGkAAABdoA/////AIAAAAD/AAA
  AAAAAAIuAAAAAAD////6AAAAAAEAAAAD+wAAAAoAcwBjAG8AcABlAQAAAAD/////AAAAAAAAAAD7
  AAAABABuAGEBAAAAAP////8AAAAAAAAAAPsAAAAEAHMAYQEAAAAA/////wAAAAAAAAAA/AAAAAAA
  AACqAAAAAAD////8AQAAAAH7AAAACABhAHMAZwBzAQAAAAAAAALqAAAAAAAAAAD8AAAAAAAAA9wA
  AANJAP////wBAAAAAvwAAAAAAAADGQAAAmMA/////AIAAAAF+wAAABoAUAB5AHIAcABsACAAYwBv
  AG4AdAByAG8AbAEAAAAAAAAA7QAAAAAAAAAA/AAAAXYAAADQAAAAAAD////6AAAAAAIAAAAC+wAA
  ACAATABpAHYAZQBfAGYAaQB0AF8AZgBpAG4AZQBzAHMAZQEAAAAA/////wAAAAAAAAAA+wAAABQA
  TQBvAHQAbwByACAAUwBjAGEAbgEAAAAA/////wAAAAAAAAAA/AAAAAAAAAISAAACBAD////6AAAA
  AgEAAAAD+wAAACAATABpAHYAZQAgAGYAaQB0ACAAZgBpAG4AZQBzAHMAZQEAAAAA/////wAAAAAA
  AAAA+wAAABQATQBvAHQAbwByACAAcwBjAGEAbgEAAAAA/////wAAAAAAAAAA+wAAAAgAUABpAGQA
  cwEAAAAAAAACYwAAAmMA////+wAAAAgAQQBzAGcAcwEAAAIWAAAAxAAAAIoA////+wAAABYAUAB5
  AHIAcABsACAAbQBvAGQAZQBsAQAAAt4AAAD+AAAAswD////8AAADHQAAA3MAAANzAP////wCAAAA
  A/sAAAAgAEwAaQB2AGUAIABGAGkAdAAgAEYAaQBuAGUAcwBzAGUBAAAAAAAAAIYAAAAAAAAAAPsA
  AAAEAE4AYQMAAAaqAAAAKAAAA3YAAAOn+wAAAB4AUwBjAG8AcABlAC8AUwBwAGUAYwAuACAAQQBu
  AC4BAAAAAAAAA9wAAADeAP///wAABpAAAAAAAAAABAAAAAQAAAAIAAAACPwAAAAA
Live fit finesse:
  length: 0.0157
  mod_freq: 50000000.0
Motor scan:
  lambda_start: 1055.0
  lambda_stop: 1080.0
  threshold: 0.05
