pyrpl: # General configuration of the software:
  name: test_refactor
  gui: true # autostart gui
  loglevel: info
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  modules: # SoftwareModules to load (in addition to IqManager, AsgManager, PidManager, ScopeManager)
    - NetworkAnalyzer
    - SpectrumAnalyzer
    - Lockbox
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAPDAAADifwBAAAAAfwAAAAAAAADwwAAAogA////+gAAAAcBAAAA
    CPsAAAAMAHMAYwBvAHAAZQBzA/////8AAAANAAADSQAAAgr7AAAACABhAHMAZwBzAAAAAAD/////
    AAAAFgD////7AAAABgBpAHEAcwAAAAAA/////wAAABYA////+wAAAAgAcABpAGQAcwAAAAAA////
    /wAAABYA////+wAAAAgAaQBpAHIAcwAAAAAA/////wAAABYA////+wAAAAQAbgBhAAAAAAD/////
    AAAAFgD////7AAAAIgBzAHAAZQBjAHQAcgB1AG0AXwBhAG4AYQBsAHkAegBlAHIAAAAAAP////8A
    AAAWAP////sAAAAOAGwAbwBjAGsAYgBvAHgBAAAAAP////8AAAKIAP///wAAA8MAAAAAAAAABAAA
    AAQAAAAIAAAACPwAAAAA
  window_position:
  - 319
  - 22
  - 963
  - 946
redpitaya:
  hostname: 10.214.1.33
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
nas: !!omap
- na: !!omap []
spectrum_analyzers: !!omap
- spectrum_analyzer: !!omap []
lockboxs: !!omap
- lockbox: !!omap
  - fabryperots: !!omap
    - FabryPerot: !!omap []
  - reflections: !!omap
    - reflection: !!omap []
  - transmissions: !!omap
    - transmission: !!omap []
  - pdhs: !!omap
    - pdh: !!omap []
  - sequences: !!omap
    - sequence: !!omap [{stages: !!omap [{stage1: !!omap [{duration: 0.0022}]}, {
              stage2: !!omap [{duration: 0.0022}]}, {stage3: !!omap [{duration: 0.0022}]}]}]
  - interferometers: !!omap
    - interferometer: !!omap []
  - direct_inputs: !!omap
    - direct_input1: !!omap []
    - direct_input2: !!omap []
  - model_name: FabryPerot
hks: !!omap
- hk: !!omap []
amss: !!omap
- ams: !!omap []
scopes: !!omap
- scope: !!omap []
samplers: !!omap
- sampler: !!omap []
asgs: !!omap
- asg1: !!omap []
- asg2: !!omap []
pwms: !!omap
- pwm1: !!omap []
- pwm2: !!omap []
pids: !!omap
- pid1: !!omap []
- pid2: !!omap []
- pid3: !!omap []
- pid4: !!omap []
iirs: !!omap
- iir: !!omap []
iqs: !!omap
- iq1: !!omap []
