pyrpl: # General configuration of the software:
  name: test_refactor
  gui: true # autostart gui
  loglevel: info
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  modules: # SoftwareModules to load (in addition to IqManager, AsgManager, PidManager, ScopeManager)
    - NetworkAnalyzer
    - SpectrumAnalyzer
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAd8AAAD3fwBAAAAAvwAAAAAAAADkAAAA0MA/////AIAAAAD+wAA
    AAwAcwBjAG8AcABlAHMBAAAAFQAAASQAAADiAP////sAAAAGAGkAcQBzAQAAAT0AAAHoAAABSgD/
    ///7AAAACABhAHMAZwBzAQAAAykAAADJAAAAegD////8AAADlAAAA+gAAAPoAP////wCAAAAAvwA
    AAAVAAABugAAAT8BAAAU+gAAAAACAAAAB/sAAAAEAG4AYQEAAAAA/////wAAAO0A////+wAAACIA
    cwBwAGUAYwB0AHIAdQBtAF8AYQBuAGEAbAB5AHoAZQByAQAAAAD/////AAAAogD////7AAAAIgBz
    AHAAZQBjAHQAcgB1AG0AIABhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAAAAAAAPsAAAAUAEIA
    YQBzAGUATQBvAGQAdQBsAGUBAAAAAP////8AAAAAAAAAAPsAAAAIAGkAaQByAHMBAAAAAP////8A
    AAEqAP////sAAAAgAG4AZQB0AHcAbwByAGsAXwBhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAA
    AAAAAPsAAAAKAHMAYwBvAHAAZQEAAAAA/////wAAAAAAAAAA+wAAAAgAcABpAGQAcwEAAAHTAAAC
    HwAAAa4A////AAAHfAAAAAAAAAAEAAAABAAAAAgAAAAI/AAAAAA=
  window_position:
  - -1928
  - 117
  - 1916
  - 1030
redpitaya:
  #hostname: 10.214.1.28 # comes from environment
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
nas: !!omap
- na: !!omap []
spectrum_analyzers: !!omap
- spectrum_analyzer: !!omap []
hks: !!omap
- hk: !!omap []
amss: !!omap
- ams: !!omap []
scopes: !!omap
- scope: !!omap
  - input1: adc1
  - duration: 0.134217728
  - trigger_source: asg1
  - trigger_delay: 0.0
  - rolling_mode: false
  - ch1_active: true
  - running_continuous: true
  - input2: adc2
  - average: true
  - threshold_ch1: 0.0
  - threshold_ch2: 0.0
  - curve_name: ''
  - ch2_active: false
- states:
    running_roll:
      average: true
      ch2_active: false
      duration: 0.536870912
      trigger_delay: 0.0
      curve_name: ''
      rolling_mode: true
      input2: adc2
      input1: adc1
      trigger_source: asg1
      running_continuous: true
      ch1_active: true
      threshold_ch2: 0.0
      threshold_ch1: 0.0
    running_triggered:
      average: true
      ch2_active: false
      duration: 0.134217728
      trigger_delay: 0.0
      curve_name: ''
      rolling_mode: false
      input2: adc2
      input1: adc1
      trigger_source: asg1
      running_continuous: true
      ch1_active: true
      threshold_ch2: 0.0
      threshold_ch1: 0.0
    stop:
      average: true
      ch2_active: false
      duration: 0.134217728
      trigger_delay: 0.0
      curve_name: ''
      rolling_mode: false
      input2: adc2
      input1: adc1
      trigger_source: asg1
      running_continuous: false
      ch1_active: true
      threshold_ch2: 0.0
      threshold_ch1: 0.0
samplers: !!omap
- sampler: !!omap []
asgs: !!omap
- asg1: !!omap
  - frequency: 99999.94654208422
- asg2: !!omap []
pwms: !!omap
- pwm1: !!omap []
- pwm2: !!omap []
iqs: !!omap
- iq1: !!omap []
- iq2: !!omap []
pids: !!omap
- pid1: !!omap []
- pid2: !!omap []
- pid3: !!omap []
- pid4: !!omap []
iirs: !!omap
- iir: !!omap []
