pyrpl:
  name: test_refactor
  gui: false
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAaQAAAD4/wBAAAAAvwAAAAAAAADHAAAAwkA/////AIAAAAD+wAA
    AAwAcwBjAG8AcABlAHMBAAAAEgAAAUAAAADWAP////sAAAAGAGkAcQBzAQAAAVgAAAHgAAABSgD/
    ///7AAAACABhAHMAZwBzAQAAAz4AAAC3AAAAegD////8AAADIgAAA24AAANuAP////wCAAAAAvwA
    AAASAAABuAAAAScBAAAU+gAAAAACAAAAB/sAAAAEAG4AYQEAAAAA/////wAAANUA////+wAAACIA
    cwBwAGUAYwB0AHIAdQBtAF8AYQBuAGEAbAB5AHoAZQByAQAAAAD/////AAAAlgD////7AAAAIgBz
    AHAAZQBjAHQAcgB1AG0AIABhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAAAAAAAPsAAAAUAEIA
    YQBzAGUATQBvAGQAdQBsAGUBAAAAAP////8AAAAAAAAAAPsAAAAIAGkAaQByAHMBAAAAAP////8A
    AAESAP////sAAAAgAG4AZQB0AHcAbwByAGsAXwBhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAA
    AAAAAPsAAAAKAHMAYwBvAHAAZQEAAAAA/////wAAAAAAAAAA+wAAAAgAcABpAGQAcwEAAAHQAAAC
    JQAAAa4A////AAAGkAAAAAAAAAAEAAAABAAAAAgAAAAI/AAAAAA=
  window_position:
  - 1362
  - -4
  - 1680
  - 1031
redpitaya:
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
nas:
  na:
    output_direct: out1
    input: in1
    start: 1000.0
    stop: 10000.0
    rbw:
    - 1214
    points: 101
    amplitude: 0.01
    avg: 1
spectrum_analyzers:
  spectrum_analyzer: {}
hks:
  hk: {}
amss:
  ams: {}
scopes:
  scope:
    trigger_source: immediately
    running_continuous: true
    input1: in1
    ch1_active: true
    ch2_active: true
    input2: in2
    duration: 0.536870912
    rolling_mode: true
samplers:
  sampler: {}
asgs:
  asg1: {}
  asg2: {}
pwms:
  pwm1: {}
  pwm2: {}
iqs:
  iq1: {}
  iq2: {}
  iq3:
    bandwidth:
    - 1214
    input: in1
    acbandwidth:
    - 0
    frequency: 999999.9892897904
    output_signal: output_direct
    gain: 0.0
    amplitude: 0.0
    phase: 0.0
    output_direct: out1
pids:
  pid1: {}
  pid2: {}
  pid3: {}
  pid4: {}
iirs:
  iir: {}
