pyrpl: # General configuration of the software:
  name: test_refactor
  gui: true # autostart gui
  loglevel: info
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  modules: # SoftwareModules to load (in addition to IqManager, AsgManager, PidManager, ScopeManager)
    - NetworkAnalyzer
    - SpectrumAnalyzer
    - Lockbox
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAT4AAAEP/wBAAAAAvwAAAAAAAAE+AAABPgA////+gAAAAACAAAA
    BfsAAAAMAHMAYwBvAHAAZQBzAQAAAAD/////AAAAwQD////7AAAABgBpAHEAcwEAAAAA/////wAA
    AUoA////+wAAAAgAYQBzAGcAcwEAAAAA/////wAAAHoA////+wAAAAgAcABpAGQAcwMAAAKIAAAA
    JwAABPgAAAQU+wAAAA4AbABvAGMAawBiAG8AeAEAAAAVAAADxwAAAsIA/////AAABOoAAANDAAAA
    AAD////8AgAAAAL8AAAAFQAAA2EAAAAAAP////oAAAACAgAAAAb7AAAABABuAGEAAAAAAP////8A
    AABQAP////sAAAAiAHMAcABlAGMAdAByAHUAbQBfAGEAbgBhAGwAeQB6AGUAcgAAAAAA/////wAA
    AFAA////+wAAACIAcwBwAGUAYwB0AHIAdQBtACAAYQBuAGEAbAB5AHoAZQByAQAAAAD/////AAAA
    AAAAAAD7AAAAFABCAGEAcwBlAE0AbwBkAHUAbABlAQAAAAD/////AAAAAAAAAAD7AAAAIABuAGUA
    dAB3AG8AcgBrAF8AYQBuAGEAbAB5AHoAZQByAQAAAAD/////AAAAAAAAAAD7AAAACgBzAGMAbwBw
    AGUBAAAAAP////8AAAAAAAAAAPsAAAAIAGkAaQByAHMAAAAAFQAAA8cAAABQAP///wAABPgAAAAA
    AAAABAAAAAQAAAAIAAAACPwAAAAA
  window_position:
  - -7
  - 0
  - 1272
  - 1128
redpitaya:
  hostname: 10.214.1.28
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
nas:
  na: {}
spectrum_analyzers:
  spectrum_analyzer: {}
hks:
  hk: {}
amss:
  ams: {}
scopes:
  scope: {trigger_source: asg2, input1: pid4, trigger_delay: 0.0, duration: 1.073741824,
    running_continuous: true, curve_name: '', input2: adc2, threshold_ch1: 0.0, threshold_ch2: 0.0,
    average: true, rolling_mode: true}
  states:
    sweep:
      curve_name: ''
      input2: adc2
      input1: pid4
      threshold_ch1: 0.0
      duration: 0.016777216
      trigger_source: asg2
      running_continuous: false
      threshold_ch2: 0.0
      trigger_delay: 0.0
      average: true
      rolling_mode: false
    sweep_running:
      curve_name: ''
      input2: adc2
      input1: pid4
      threshold_ch1: 0.0
      duration: 0.016777216
      trigger_source: asg2
      running_continuous: true
      threshold_ch2: 0.0
      trigger_delay: 0.0
      average: true
      rolling_mode: false
    rolling:
      rolling_mode: true
      trigger_source: asg2
      input1: pid4
      average: true
      threshold_ch2: 0.0
      input2: adc2
      trigger_delay: 0.0
      duration: 1.073741824
      running_continuous: true
      curve_name: ''
      threshold_ch1: 0.0
samplers:
  sampler: {}
asgs:
  asg2: {waveform: ramp, offset: 0.0, frequency: 1.0477378964424133, amplitude: 1.0,
    output_direct: off}
  asg1: {frequency: 100.000761449337}
  states: {uiui: {amplitude: 1.0, waveform: sin, trigger_source: immediately, output_direct: off,
      offset: 0.0, frequency: 0.0}}
pwms:
  pwm2: {}
  pwm1: {}
iqs:
  iq1: {output_direct: out1, frequency: 49999999.98835847, amplitude: 1.0, phase: 90.0,
    quadrature_factor: 0.01171875, gain: 0.0, input: adc1, output_signal: quadrature}
  iq2:
    frequency: 0
  iq3:
    bandwidth:
    - 151
    amplitude: 1.0
    output_signal: quadrature
    input: adc1
    gain: 0.0
    frequency: 0.9895302355289459
    phase: 0.0
    output_direct: out1
    quadrature_factor: 0.01171875
pids:
  pid2:
    ival: 0.0
    p: 0.0
  pid4:
    ival: 0.0
    p: 1.0
    i: 0.0
    input: asg2
    output_direct: out1
    setpoint: 0.0
    inputfilter:
    - 0
    - 0
    - 0
    - 0
  pid3:
    ival: 0.0
  pid1:
    ival: 0.0
    setpoint: 0.0
    p: 0.0
    input: asg1
    i: 10.000527898530768
    d: 0.0
iirs:
  iir:
    loops: 5
    zeros:
    - (22.37112029802451+0j)
states: {VOU: {offset: 0.0, frequency: 0.0, waveform: sin, output_direct: off, trigger_source: immediately,
    amplitude: 1.0}}
lockboxs:
  lockbox:
    pdhs:
      states:
        pdh_freq30:
          adc: adc1
          mod_freq: 3.360189132690429
          mod_output: out1
          mod_amp: 0.0
          mod_phase: 0.0
        coucou:
          mod_freq: 3.360189132690429
          adc: adc1
          mod_output: out1
          mod_amp: 0.0
          mod_phase: 0.0
      pdh:
        mod_freq: 50000000.0
        adc: adc1
        mod_output: out1
        mod_amp: 1.0
        mod_phase: 0.0
    reflections:
      reflection: {adc: adc2}
    transmissions:
      transmission: {}
    model: FabryPerot
    direct_inputs:
      direct_input1: {}
      direct_input2: {adc: adc2}
    outputs:
      states:
        slow_today:
          additional_filter:
          - 0
          - 0
          - 0
          - 0
          sweep_amplitude: 0.0
          dc_gain: 0.038320936203002934
          sweep_waveform: cos
          unity_gain_desired: 0.0
          p: 0.0
          tf_curve: 0
          i: -0.0011
          tf_type: curve
          is_sweepable: false
          name: slow_piezo
          extra_module: None
          sweep_frequency: 0.0
          sweep_offset: 0.0
          output_channel: dac1
          extra_module_state: None
        iuiu:
          additional_filter:
          - 0
          - 0
          - 0
          - 0
          sweep_amplitude: 0.0
          dc_gain: 0.038320936203002934
          sweep_waveform: cos
          unity_gain_desired: 0.0
          p: 0.0
          tf_curve: 0
          i: -0.0011
          tf_type: curve
          is_sweepable: false
          name: slow_piezo
          extra_module: None
          sweep_frequency: 0.0
          sweep_offset: 0.0
          output_channel: dac1
          extra_module_state: None
      slow_piezo: !!omap
      - name: slow_piezo
      - dc_gain: 421.4735386635911
      - analog_filter:
        - 1831.1844489391813
        - 0.0
        - 0.0
        - 0.0
      - sweep_frequency: 100.0
      - sweep_amplitude: 1.0
      - sweep_waveform: ramp
      - is_sweepable: true
      - p: 20.804416063489814
      - i: 38096.723164723044
      - unity_gain_desired: 38096.723164723044
      - additional_filter:
        - 0
        - 0
        - 0
        - 0
      - tf_type: flat
      - assisted_design: true
      - tf_curve: 40
    fabryperots: !!omap
    - FabryPerot: !!omap [{eta: 1.0}, {length: 0.0}, {wavelength: 1030.0}, {finesse: 0.0}]
    sequences: !!omap
    - sequence: !!omap [{stages: !!omap [{stage1: !!omap [{output_on: {slow_piezo: [
                      true, false, 0]}}, {name: stage1}, {duration: 10.17514314613342},
                {variable_value: 0.3236037654876708}]}, {stage2: !!omap [{output_on: {
                    slow_piezo: [true, false, 0]}}, {name: stage2}]}]}]
    auto_relock: false
    interferometers: !!omap
    - interferometer: !!omap []
    model_name: interferometer
