pyrpl: # General configuration of the software:
  name: test_refactor
  gui: true # autostart gui
  loglevel: info
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  modules: # SoftwareModules to load (in addition to IqManager, AsgManager, PidManager, ScopeManager)
    - NetworkAnalyzer
    - SpectrumAnalyzer
    - Lockbox
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAgAAAAAAAAeAAAABSvwCAAAAAfsAAAAGAGkAcQBzAgAAAAAAAALuAAAHgAAA
    AUoAAAACAAAE5gAAA8f8AQAAAAP7AAAADgBsAG8AYwBrAGIAbwB4AQAAAAAAAATmAAAE5gD////7
    AAAACABhAHMAZwBzAAAAAAAAAAeAAAAAFgD////8AAAFrQAAAlcAAAAAAP////wCAAAAAvwAAAAV
    AAADYQAAAAAA////+gAAAAICAAAABvsAAAAEAG4AYQAAAAAA/////wAAAFAA////+wAAACIAcwBw
    AGUAYwB0AHIAdQBtAF8AYQBuAGEAbAB5AHoAZQByAAAAAAD/////AAAAUAD////7AAAAIgBzAHAA
    ZQBjAHQAcgB1AG0AIABhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAAAAAAAPsAAAAUAEIAYQBz
    AGUATQBvAGQAdQBsAGUBAAAAAP////8AAAAAAAAAAPsAAAAgAG4AZQB0AHcAbwByAGsAXwBhAG4A
    YQBsAHkAegBlAHIBAAAAAP////8AAAAAAAAAAPsAAAAKAHMAYwBvAHAAZQEAAAAA/////wAAAAAA
    AAAA/AAAABUAAAQ/AAAAAAD////6/////wEAAAAD+wAAAAgAaQBpAHIAcwAAAAAA/////wAAABYA
    ////+wAAAAwAcwBjAG8AcABlAHMAAAAAAP////8AAAAWAP////sAAAAIAHAAaQBkAHMAAAADbwAA
    BA0AAAAWAP///wAABOYAAAAAAAAABAAAAAQAAAAIAAAACPwAAAAA
  window_position:
  - -1927
  - 125
  - 1254
  - 1008
redpitaya:
  hostname: 10.214.1.28
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
nas:
  na: {}
spectrum_analyzers:
  spectrum_analyzer: {}
hks:
  hk: {}
amss:
  ams: {}
scopes:
  scope: {}
samplers:
  sampler: {}
asgs:
  asg2: {}
  asg1: {}
  states: {uiui: {amplitude: 1.0, waveform: sin, trigger_source: immediately, output_direct: off,
      offset: 0.0, frequency: 0.0}}
pwms:
  pwm2: {}
  pwm1: {}
iqs:
  iq1: {output_direct: out1, frequency: 3.346940502524376, amplitude: 0.0, phase: 0.0,
    quadrature_factor: 0.01171875, gain: 0.0, input: adc1, output_signal: quadrature}
  iq2:
    frequency: 0
  iq3:
    bandwidth:
    - 151
pids:
  pid2:
    ival: 0.0
  pid4:
    ival: 0.0
  pid3:
    ival: 0.0
  pid1:
    ival: 0.0
    setpoint: 0.1365966796875
iirs:
  iir:
    loops: 5
    zeros:
    - (22.37112029802451+0j)
states: {VOU: {offset: 0.0, frequency: 0.0, waveform: sin, output_direct: off, trigger_source: immediately,
    amplitude: 1.0}}
lockboxs:
  lockbox:
    pdhs:
      states:
        pdh_freq30:
          adc: adc1
          mod_freq: 3.360189132690429
          mod_output: out1
          mod_amp: 0.0
          mod_phase: 0.0
        coucou:
          mod_freq: 3.360189132690429
          adc: adc1
          mod_output: out1
          mod_amp: 0.0
          mod_phase: 0.0
      pdh:
        mod_freq: 3.360189132690429
        adc: adc1
        mod_output: out1
        mod_amp: 0.0
        mod_phase: 0.0
    reflections:
      reflection: {adc: adc2}
    transmissions:
      transmission: {}
    model: FabryPerot
    direct_inputs:
      direct_input1: {}
      direct_input2: {adc: adc2}
    outputs:
      states:
        slow_today:
          additional_filter:
          - 0
          - 0
          - 0
          - 0
          sweep_amplitude: 0.0
          dc_gain: 0.038320936203002934
          sweep_waveform: cos
          unity_gain_desired: 0.0
          p: 0.0
          tf_curve: 0
          i: -0.0011
          tf_type: curve
          is_sweepable: false
          name: slow_piezo
          extra_module: None
          sweep_frequency: 0.0
          sweep_offset: 0.0
          output_channel: dac1
          extra_module_state: None
        iuiu:
          additional_filter:
          - 0
          - 0
          - 0
          - 0
          sweep_amplitude: 0.0
          dc_gain: 0.038320936203002934
          sweep_waveform: cos
          unity_gain_desired: 0.0
          p: 0.0
          tf_curve: 0
          i: -0.0011
          tf_type: curve
          is_sweepable: false
          name: slow_piezo
          extra_module: None
          sweep_frequency: 0.0
          sweep_offset: 0.0
          output_channel: dac1
          extra_module_state: None
      output: !!omap
      - is_sweepable: false
      - tf_type: filter
      - extra_module: iir
      - p: 0.05727552947998048
      - i: 0.0012465007781982376
      - analog_filter:
        - 1371.6295934249456
        - 0.0
        - 0.0
        - 0.0
      slow_piezo: !!omap
      - name: slow_piezo
      - dc_gain: 0.0
      - analog_filter:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      - unity_gain_desired: 0.06380385932922364
      - p: 0.0622656147003174
      - i: 0.09783168029785158
    models:
      interferometer:
        wavelength: 0.9
      FabryPerot:
        finesse: 1.0
        length: 1.0
        wavelength: 0.1064
      states:
        FPM:
          wavelength: 0.1064
          finesse: 1.0
          length: 1.0
    fabryperots: !!omap
    - FabryPerot: !!omap
      - wavelength: 1064.0
      - finesse: 40000.0
      - length: 0.001
    - states:
        FPM:
          finesse: 40000.0
          wavelength: 1064.0
          length: 0.001
    interferometers: !!omap
    - interferometer: !!omap
      - wavelength: 1064.0
    - states:
        mech_memnbrane:
          wavelength: 1064.0

    sequences: !!omap
    - sequence: !!omap
      - stages: !!omap
        - stage1: !!omap
          - output_on:
              slow_piezo:
              - true
              - false
              - 0
              output:
              - true
              - false
              - 0
          - name: stage1
        - stage3: !!omap
          - output_on:
              slow_piezo:
              - true
              - false
              - 0
              output:
              - true
              - false
              - 0
          - name: stage3
        - stage4: !!omap
          - output_on:
              slow_piezo:
              - true
              - false
              - 0
              output:
              - true
              - false
              - 0
          - name: stage4
        - stage5: !!omap
          - output_on:
              slow_piezo:
              - true
              - false
              - 0
              output:
              - true
              - false
              - 0
          - name: stage5
