pyrpl: # General configuration of the software:
  name: test_refactor
  gui: true # autostart gui
  loglevel: info
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  modules: # SoftwareModules to load (in addition to IqManager, AsgManager, PidManager, ScopeManager)
    - NetworkAnalyzer
    - SpectrumAnalyzer
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAd8AAAD3fwBAAAAAvwAAAAAAAADrAAAA40A/////AIAAAAD+wAA
    AAwAcwBjAG8AcABlAHMBAAAAFQAAASQAAADXAP////sAAAAGAGkAcQBzAQAAAT0AAAHoAAABaAD/
    ///7AAAACABhAHMAZwBzAQAAAykAAADJAAAAlAD////8AAADsAAAA8wAAAOmAP////wCAAAAAvwA
    AAAVAAABugAAARMBAAAU+gAAAAACAAAAB/sAAAAEAG4AYQEAAAAA/////wAAAP4A////+wAAACIA
    cwBwAGUAYwB0AHIAdQBtAF8AYQBuAGEAbAB5AHoAZQByAQAAAAD/////AAAAswD////7AAAAIgBz
    AHAAZQBjAHQAcgB1AG0AIABhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAAAAAAAPsAAAAUAEIA
    YQBzAGUATQBvAGQAdQBsAGUBAAAAAP////8AAAAAAAAAAPsAAAAIAGkAaQByAHMBAAAAAP////8A
    AAB/AP////sAAAAgAG4AZQB0AHcAbwByAGsAXwBhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAA
    AAAAAPsAAAAKAHMAYwBvAHAAZQEAAAAA/////wAAAAAAAAAA+wAAAAgAcABpAGQAcwEAAAHTAAAC
    HwAAAhgA////AAAHfAAAAAAAAAAEAAAABAAAAAgAAAAI/AAAAAA=
  window_position:
  - -1928
  - 117
  - 1916
  - 1030
redpitaya:
  hostname: 10.214.1.28
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
asg1:
  amplitude: 1.0
  waveform: sin
  offset: 0.0
  output_direct: off
  frequency: 1000000.0474974513
  trigger_source: immediately
asg2:
  amplitude: 1.0
  waveform: sin
  offset: 0.0
  output_direct: off
  frequency: 0.0
  trigger_source: immediately
asgs: {}
iqs: {}
pids: {}
scopes: {}
iirs: {}
na:
  start: 1000000.0
  input: adc1
  stop: 2000000.0
  rbw:
  - 77712.0
  output_direct: out1
  acbandwidth:
  - 0.0
  curve_name: na_curve
spectrum_analyzer:
  window: flattop
  input: asg1
  span: 100000.0
  center: 1000000.0
hk: {}
ams: {}
scope:
  trigger_delay: 0
  trigger_source: immediately
  input2: adc2
  input1: adc1
  average: true
sampler: {}
adc1: {}
adc2: {}
iq1:
  output_signal: quadrature
  bandwidth:
  - 0.0
  - 0.0
  input: adc1
pid1:
  inputfilter:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  input: adc1
pid2:
  inputfilter:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  input: adc2
pid3:
  inputfilter:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  input: adc1
pid4:
  inputfilter:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  input: adc2
iir:
  input: adc1
