pyrpl: # General configuration of the software:
  name: test_refactor
  gui: true # autostart gui
  loglevel: info
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  modules: # SoftwareModules to load (in addition to IqManager, AsgManager, PidManager, ScopeManager)
    - NetworkAnalyzer
    - SpectrumAnalyzer
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAevAAAESPwBAAAAAvwAAAAAAAADjQAAA40A/////AIAAAAD+wAA
    AAwAcwBjAG8AcABlAHMBAAAAFQAAAUQAAADXAP////sAAAAGAGkAcQBzAQAAAV0AAAIdAAABaAD/
    ///7AAAACABhAHMAZwBzAQAAA34AAADfAAAAlAD////8AAADkQAABB4AAAQeAP////wCAAAAAvwA
    AAAVAAAB6gAAARMBAAAU+gAAAAQCAAAAB/sAAAAEAG4AYQEAAAAA/////wAAAP4A////+wAAACIA
    cwBwAGUAYwB0AHIAdQBtAF8AYQBuAGEAbAB5AHoAZQByAQAAAAD/////AAAAswD////7AAAAIgBz
    AHAAZQBjAHQAcgB1AG0AIABhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAAAAAAAPsAAAAUAEIA
    YQBzAGUATQBvAGQAdQBsAGUBAAAAAP////8AAAAAAAAAAPsAAAAIAGkAaQByAHMBAAAAAP////8A
    AACcAP////sAAAAgAG4AZQB0AHcAbwByAGsAXwBhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAA
    AAAAAPsAAAAKAHMAYwBvAHAAZQEAAAAA/////wAAAAAAAAAA+wAAAAgAcABpAGQAcwEAAAIDAAAC
    WgAAAhgA////AAAHrwAAAAAAAAAEAAAABAAAAAgAAAAI/AAAAAA=
  window_position:
  - -8
  - -8
  - 1967
  - 1137
redpitaya:
  hostname: 10.214.1.28
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
asg1:
  amplitude: 1.0
  waveform: sin
  offset: 0.0
  output_direct: off
  frequency: 0.0
  trigger_source: immediately
asg2:
  amplitude: 1.0
  waveform: sin
  offset: 0.0
  output_direct: off
  frequency: 0.0
  trigger_source: immediately
asgs: {}
iqs: {}
pids: {}
scopes: {}
iirs: {}
na:
  start: 100000.0
  input: adc1
  stop: 2000000.0
  rbw:
  - 9714.0
  output_direct: out1
  acbandwidth:
  - 0.0
  curve_name: na_curve
spectrum_analyzer:
  window: flattop
  input: asg1
  span:
  - 122071.0
  center: 1000000.0
hk: {}
ams: {}
scope:
  trigger_delay: 0
  trigger_source: immediately
  input2: adc2
  input1: adc1
  average: true
sampler: {}
adc1: {}
adc2: {}
iq1:
  output_signal: quadrature
  bandwidth:
  - 0.0
  - 0.0
  input: adc1
  output_direct: off
pid1:
  inputfilter:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  input: adc1
  output_direct: off
pid2:
  inputfilter:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  input: adc2
  output_direct: off
pid3:
  inputfilter:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  input: adc1
  output_direct: off
pid4:
  inputfilter:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  input: adc2
  output_direct: off
iir:
  input: adc1
  output_direct: off
  on: true
  shortcut: false
  loops: 5
  zeros:
  - (0.417+1.55j)
  - (2.682+2.605j)
  poles:
  - (2.607+0.418j)
