pyrpl:
  name: test_refactor
  gui: true
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  - Lockbox
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAf9AAAD3fwBAAAAAvwAAAAAAAAEEQAAAAAA/////AIAAAAE+wAA
    AAwAcwBjAG8AcABlAHMAAAAAFQAAASQAAABQAP////sAAAAGAGkAcQBzAAAAABUAAAK6AAAAUAD/
    ///7AAAACABhAHMAZwBzAAAAABUAAAPdAAAAUAD////7AAAADgBsAG8AYwBrAGIAbwB4AAAAAAD/
    ////AAAAUAD////8AAAAAAAAB/0AAAAAAP////wCAAAAAvwAAAAVAAABugAAAAAA////+gAAAAIC
    AAAAB/sAAAAEAG4AYQAAAAAA/////wAAAFAA////+wAAACIAcwBwAGUAYwB0AHIAdQBtAF8AYQBu
    AGEAbAB5AHoAZQByAAAAAAD/////AAAAUAD////7AAAAIgBzAHAAZQBjAHQAcgB1AG0AIABhAG4A
    YQBsAHkAegBlAHIBAAAAAP////8AAAAAAAAAAPsAAAAUAEIAYQBzAGUATQBvAGQAdQBsAGUBAAAA
    AP////8AAAAAAAAAAPsAAAAIAGkAaQByAHMAAAAAAP////8AAABQAP////sAAAAgAG4AZQB0AHcA
    bwByAGsAXwBhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAAAAAAAPsAAAAKAHMAYwBvAHAAZQEA
    AAAA/////wAAAAAAAAAA+wAAAAgAcABpAGQAcwAAAAAVAAAD3QAAAFAA////AAAAAAAAAAAAAAAE
    AAAABAAAAAgAAAAI/AAAAAA=
  window_position:
  - 54
  - 103
  - 2045
  - 1030
redpitaya:
  hostname: 10.214.1.28
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
nas:
  na:
    output_direct: out1
    input: adc1
    start: 1000000.0
    stop: 2000000.0
    rbw:
    - 77712
spectrum_analyzers:
  spectrum_analyzer:
    input: asg1
hks:
  hk: {}
amss:
  ams: {}
scopes:
  scope: {}
samplers:
  sampler: {}
asgs:
  asg1: {}
  asg2: {}
pwms:
  pwm1: {}
  pwm2: {}
iqs:
  iq1: {}
  iq3:
    bandwidth:
    - 77712
    input: adc1
    acbandwidth:
    - 0
    frequency: 1904000.0042878091
    output_signal: output_direct
    gain: 0.0
    amplitude: 0.01000213623046875
    phase: 0.0
    output_direct: out1
pids:
  pid1: {}
  pid2: {}
  pid3: {}
  pid4: {}
iirs:
  iir: {}
lockboxs: !!omap
- lockbox: !!omap
  - fabryperots: !!omap
    - FabryPerot: !!omap []
  - transmissions: !!omap
    - transmission: !!omap []
  - reflections: !!omap
    - reflection: !!omap []
  - pdhs: !!omap
    - pdh: !!omap []
  - sequences: !!omap
    - sequence: !!omap []

