pyrpl: # General configuration of the software:
  name: test_refactor
  gui: true # autostart gui
  loglevel: info
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  modules: # SoftwareModules to load (in addition to IqManager, AsgManager, PidManager, ScopeManager)
    - NetworkAnalyzer
    - SpectrumAnalyzer
    - Lockbox
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAgAAAAAAAAd8AAAD3fwCAAAAAfsAAAAGAGkAcQBzAAAAABUAAAPdAAAAUAD/
    //8AAAACAAAHfAAAA9D8AQAAAAL8AAAAAAAABSEAAAH1AP////wCAAAAA/sAAAAMAHMAYwBvAHAA
    ZQBzAAAAABUAAAPdAAAAUAD////7AAAACABhAHMAZwBzAAAAAykAAADJAAAAUAD////7AAAADgBs
    AG8AYwBrAGIAbwB4AQAAABUAAAPQAAACIgD////8AAAFJQAAAlcAAAJXAP////wCAAAAAvwAAAAV
    AAAD3QAAAAAA////+gAAAAICAAAAB/sAAAAEAG4AYQAAAAAA/////wAAAFAA////+wAAACIAcwBw
    AGUAYwB0AHIAdQBtAF8AYQBuAGEAbAB5AHoAZQByAAAAAAD/////AAAAUAD////7AAAAIgBzAHAA
    ZQBjAHQAcgB1AG0AIABhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAAAAAAAPsAAAAUAEIAYQBz
    AGUATQBvAGQAdQBsAGUBAAAAAP////8AAAAAAAAAAPsAAAAIAGkAaQByAHMAAAAAAP////8AAABQ
    AP////sAAAAgAG4AZQB0AHcAbwByAGsAXwBhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAAAAAA
    APsAAAAKAHMAYwBvAHAAZQEAAAAA/////wAAAAAAAAAA+wAAAAgAcABpAGQAcwEAAAAVAAAD0AAA
    Aa4A////AAAHfAAAAAAAAAAEAAAABAAAAAgAAAAI/AAAAAA=
  window_position:
  - -8
  - -8
  - 1916
  - 1017
redpitaya:
  hostname: 10.214.1.28
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
nas:
  na: {}
spectrum_analyzers:
  spectrum_analyzer: {}
hks:
  hk: {}
amss:
  ams: {}
scopes:
  scope: {}
samplers:
  sampler: {}
asgs:
  asg2: {}
  asg1: {}
pwms:
  pwm2: {}
  pwm1: {}
iqs:
  iq1: {}
pids:
  pid2:
    ival: 0.0
  pid4:
    ival: 0.0
  pid3:
    ival: 0.0
  pid1:
    ival: 0.0
iirs:
lockboxs:
  lockbox: {direct_inputs: {direct_input1: {adc: adc1}, direct_input2: {adc: adc2}},
    outputs: {fast_piezo: {name: fast_piezo, dc_gain: -0.08492764892578127}, laser: {
        name: laser, is_sweepable: false}, slow_piezo: {output_channel: dac2, name: slow_piezo,
        dc_gain: 0.09710760307312014}}, models: {interferometer: {wavelength: 0.1064}}}
