pyrpl: # General configuration of the software:
  name: test_refactor
  gui: true # autostart gui
  loglevel: info
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  modules: # SoftwareModules to load (in addition to IqManager, AsgManager, PidManager, ScopeManager)
    - NetworkAnalyzer
    - SpectrumAnalyzer
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAeAAAAESPwBAAAAAvwAAAAAAAAHgAAABpsA/////AEAAAAC/AAA
    AAAAAAMcAAACeQD////8AgAAAAL7AAAACABhAHMAZwBzAQAAABUAAACUAAAAlAD////7AAAACABw
    AGkAZABzAQAAAK0AAAOwAAACGAD////8AAADIAAABGAAAAQeAP////wCAAAAA/wAAAAVAAABfQAA
    AX0BAAAU+gAAAAABAAAAAvsAAAAGAGkAcQBzAQAAAAD/////AAADiQD////7AAAACABpAGkAcgBz
    AQAAA18AAAQhAAAD7gD////7AAAABABuAGEBAAABlgAAAWkAAAD+AP////wAAAMDAAABWgAAAOwB
    AAAU+gAAAAACAAAAAvsAAAAMAHMAYwBvAHAAZQBzAQAAAAD/////AAAA1wD////7AAAAIgBzAHAA
    ZQBjAHQAcgB1AG0AXwBhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAACzAP////wAAAPqAAADlgAA
    AAAA////+gAAAAACAAAABPsAAAAiAHMAcABlAGMAdAByAHUAbQAgAGEAbgBhAGwAeQB6AGUAcgEA
    AAAA/////wAAAAAAAAAA+wAAABQAQgBhAHMAZQBNAG8AZAB1AGwAZQEAAAAA/////wAAAAAAAAAA
    +wAAACAAbgBlAHQAdwBvAHIAawBfAGEAbgBhAGwAeQB6AGUAcgEAAAAA/////wAAAAAAAAAA+wAA
    AAoAcwBjAG8AcABlAQAAAAD/////AAAAAAAAAAAAAAeAAAAAAAAAAAQAAAAEAAAACAAAAAj8AAAA
    AA==
  window_position:
  - -8
  - -8
  - 1920
  - 1137
redpitaya:
  hostname: 10.214.1.28
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
asg1:
  frequency: 0
  waveform: sin
  trigger_source: immediately
  offset: 0.0
  amplitude: 1.0
  output_direct: off
asg2:
  frequency: 0
  waveform: sin
  trigger_source: immediately
  offset: 0.0
  amplitude: 1.0
  output_direct: off
asgs: {}
iqs: {}
pids: {}
scopes: {}
iirs: {}
na:
  acbandwidth:
  - 0
  curve_name: na_curve
  rbw:
  - 151
  output_direct: off
  input: adc1
  stop: 50000.0
  start: 200.0
spectrum_analyzer:
  window: flattop
  input: adc1
hk: {}
ams: {}
scope:
  input2: adc2
  trigger_delay: 0.0
  trigger_source: immediately
  input1: adc1
  average: true
sampler: {}
adc1: {}
adc2: {}
iq1:
  bandwidth:
  - 0
  - 0
  output_signal: quadrature_hf
  output_direct: off
  input: adc1
  quadrature_factor: 0.0
pid1:
  inputfilter:
  - 0
  - 0
  - 0
  - 0
  output_direct: off
  input: adc1
  setpoint: -0.00048828125
pid2:
  inputfilter:
  - 0
  - 0
  - 0
  - 0
  output_direct: off
  input: adc2
pid3:
  inputfilter:
  - 0
  - 0
  - 0
  - 0
  output_direct: off
  input: adc1
pid4:
  inputfilter:
  - 0
  - 0
  - 0
  - 0
  output_direct: off
  input: adc2
iir:
  output_direct: off
  input: adc1
