pyrpl: # General configuration of the software:
  name: test_refactor
  gui: true # autostart gui
  loglevel: info
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  modules: # SoftwareModules to load (in addition to IqManager, AsgManager, PidManager, ScopeManager)
    - NetworkAnalyzer
    - NetworkAnalyzer
  window_position:
  - -8
  - -8
  - 1916
  - 1017
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAd8AAAD0PwBAAAAAfwAAAAAAAAHfAAABy8A/////AIAAAAD/AAA
    ABUAAAHTAAABXwD////8AQAAAAL8AAAAAAAAA5AAAANDAP////oAAAACAQAAAAP7AAAAIgBzAHAA
    ZQBjAHQAcgB1AG0AXwBhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAAAAAAAPsAAAAGAGkAcQBz
    AQAAAAD/////AAADQwD////7AAAACABhAHMAZwBzAQAAAAAAAAd8AAACMQD////8AAADlAAAA+gA
    AAPoAP////oAAAAAAgAAAAL7AAAABgBuAGEAMgEAAAAA/////wAAAO0A////+wAAAAwAcwBjAG8A
    cABlAHMBAAAAFQAAAdMAAADBAP////wAAAHsAAAB+QAAAcMA/////AEAAAAC+wAAAAgAaQBpAHIA
    cwEAAAAAAAADjAAAAxQA/////AAAA5AAAAPsAAAD6AD////6AAAAAgIAAAAD+wAAAAYAbgBhADEB
    AAAAAP////8AAADtAP////sAAAAEAG4AYQEAAAAA/////wAAAAAAAAAA+wAAAAgAcABpAGQAcwEA
    AAJbAAABrgAAAa4A////+wAAAAQAbgBhAAAAA3UAAADoAAAAAAAAAAAAAAd8AAAAAAAAAAQAAAAE
    AAAACAAAAAj8AAAAAA==
redpitaya:
  hostname: 10.214.1.28
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
nas:
  na: {}
  na1: {}
  na2: {input: iir, logscale: true, stop: 500000.0, rbw: [607]}
  states:
    measure_iir:
      input: iir
      infer_open_loop_tf: false
      curve_name: na_curve
      rbw: 607.1279262233556
      points: 1001
      amplitude: 0.01
      maxamplitude: 1.0
      avg: 1
      stop: 500000.0
      logscale: true
      start: 200.0
      acbandwidth: 0
      output_direct: off
      stabilize: false
spectrum_analyzers:
  spectrum_analyzer: {}
hks:
  hk: {}
amss:
  ams: {}
scopes:
  scope: {trigger_source: immediately}
samplers:
  sampler: {}
asgs:
  asg2: {}
  asg1: {}
pwms:
  pwm1: {}
  pwm2: {}
iqs:
  iq1: {output_signal: quadrature, bandwidth: [0, 0], input: adc1, frequency: 0, acbandwidth: [
      0], phase: 180.0, quadrature_factor: 0.0, output_direct: off, gain: 0.0, amplitude: 0.0}
  states: {yoyo: {output_direct: off, bandwidth: [0, 0], input: adc1, amplitude: 0.0,
      gain: 0.0, phase: 0.0, acbandwidth: 0, quadrature_factor: 0.0, output_signal: quadrature,
      frequency: 0.0}, phase90: {output_signal: quadrature, bandwidth: [0, 0], quadrature_factor: 0.0,
      input: adc1, frequency: 0.0, acbandwidth: 0, phase: 90.0, output_direct: off,
      gain: 0.0, amplitude: 0.0}, phase180: {output_signal: quadrature, bandwidth: [
        0, 0], quadrature_factor: 0.0, input: adc1, frequency: 0.0, acbandwidth: 0,
      phase: 180.0, output_direct: off, gain: 0.0, amplitude: 0.0}}
  iq3:
    amplitude: 0.0
    gain: 0.0
    output_signal: output_direct
    output_direct: off
    phase: 0.0
    bandwidth:
    - 151
    input: adc1
    acbandwidth:
    - 0
    frequency: 17879.006918519735
  iq2:
    frequency: 211.26470528542995
    bandwidth:
    - 607
    gain: 0.0
    input: iir
    output_direct: off
    amplitude: 0.0
    acbandwidth:
    - 0
    phase: 0.0
    output_signal: output_direct
pids:
  pid3: {ival: 0.0}
  pid2: {ival: 0.0}
  pid4: {ival: 0.0}
  pid1: {ival: 0.0, output_direct: off, d: 0.0, setpoint: 0.0, p: 0.0, inputfilter: [
      0, 0, 0, 0], input: adc1, i: 0.0}
  states: {iui: {output_direct: off, d: 0.0, setpoint: 0.0, p: 0.0, inputfilter: [
        0, 0, 0, 0], input: adc1, ival: 0.0, i: 0.0}}
iirs:
  iir: {poles: [(-4991.050787419987-21899.69745048423j), (-1000-37552.162547706896j)],
    loops: 5, gain: 0.02901415596008301, zeros: [(-100-947.7629626775897j)], output_direct: off,
    inputfilter: [0], input: iq2}
  states:
    2poles1zero:
      output_direct: off
      poles:
      - (-4790.056348998796-21899.69745048423j)
      - (-1000-37552.162547706896j)
      inputfilter: 0
      gain: 0.02901415596008301
      loops: 5
      input: adc1
      zeros:
      - (-100-947.7629626775897j)
