pyrpl:
  name: test_refactor
  gui: true
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAd8AAAD4vwBAAAAAvwAAAAAAAADqwAAAwkA/////AIAAAAD+wAA
    AAwAcwBjAG8AcABlAHMBAAAAEgAAASQAAADWAP////sAAAAGAGkAcQBzAQAAATwAAAHpAAABSgD/
    ///7AAAACABhAHMAZwBzAQAAAysAAADJAAAAegD////8AAADsQAAA8sAAANuAP////wCAAAAAvwA
    AAASAAABuwAAAScBAAAU+gAAAAACAAAAB/sAAAAEAG4AYQEAAAAA/////wAAANUA////+wAAACIA
    cwBwAGUAYwB0AHIAdQBtAF8AYQBuAGEAbAB5AHoAZQByAQAAAAD/////AAAAlgD////7AAAAIgBz
    AHAAZQBjAHQAcgB1AG0AIABhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAAAAAAAPsAAAAUAEIA
    YQBzAGUATQBvAGQAdQBsAGUBAAAAAP////8AAAAAAAAAAPsAAAAIAGkAaQByAHMBAAAAAP////8A
    AAESAP////sAAAAgAG4AZQB0AHcAbwByAGsAXwBhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAA
    AAAAAPsAAAAKAHMAYwBvAHAAZQEAAAAA/////wAAAAAAAAAA+wAAAAgAcABpAGQAcwEAAAHTAAAC
    IQAAAa4A////AAAHfAAAAAAAAAAEAAAABAAAAAgAAAAI/AAAAAA=
  window_position:
  - -1928
  - 117
  - 1916
  - 1030
redpitaya:
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
nas:
  na: {}
spectrum_analyzers:
  spectrum_analyzer: {}
hks:
  hk: {}
amss:
  ams: {}
scopes:
  scope: {}
samplers:
  sampler: {}
asgs:
  asg1: {}
  asg2: {}
pwms:
  pwm1: {}
  pwm2: {}
iqs:
  iq1: {}
  iq2: {}
pids:
  pid1: {}
  pid2: {}
  pid3: {}
  pid4: {}
iirs:
  iir: {}
