pyrpl:
  name: test_refactor
  gui: true
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  dock_positions: !!binary |
    AAAA/wAAAAD9AAAAAQAAAAIAAAcBAAAD4/wBAAAAAvwAAAAAAAAD8QAAA/EA/////AIAAAAD+wAA
    AAwAcwBjAG8AcABlAHMBAAAAEgAAA+MAAAC5AP////sAAAAGAGkAcQBzAAAAAQwAAAGjAAAARgD/
    ///7AAAACABhAHMAZwBzAAAAAioAAACFAAAARgD////8AAAD9wAAAwoAAAMKAP////wCAAAAAvwA
    AAASAAAD4wAAAJYA////+gAAAAECAAAAB/sAAAAEAG4AYQAAAAAA/////wAAAEYA////+wAAACIA
    cwBwAGUAYwB0AHIAdQBtAF8AYQBuAGEAbAB5AHoAZQByAQAAAAD/////AAAAlgD////7AAAAIgBz
    AHAAZQBjAHQAcgB1AG0AIABhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAAAAAAAPsAAAAUAEIA
    YQBzAGUATQBvAGQAdQBsAGUBAAAAAP////8AAAAAAAAAAPsAAAAIAGkAaQByAHMAAAAAAP////8A
    AABGAP////sAAAAgAG4AZQB0AHcAbwByAGsAXwBhAG4AYQBsAHkAegBlAHIBAAAAAP////8AAAAA
    AAAAAPsAAAAKAHMAYwBvAHAAZQEAAAAA/////wAAAAAAAAAA+wAAAAgAcABpAGQAcwAAAAASAAAD
    4wAAAEYA////AAAHAQAAAAAAAAAEAAAABAAAAAgAAAAI/AAAAAA=
  window_position:
  - 1362
  - -4
  - 1793
  - 1031
redpitaya:
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server
nas:
  na: {}
spectrum_analyzers:
  spectrum_analyzer:
    input: adc1
    baseband: true
    span:
    - 1908
    avg: 10
hks:
  hk: {}
amss:
  ams: {}
scopes:
  scope:
    trigger_source: immediately
    running_continuous: false
    duration: 0.004194304
    rolling_mode: false
samplers:
  sampler: {}
asgs:
  asg1: {}
  asg2: {}
pwms:
  pwm1: {}
  pwm2: {}
iqs:
  iq1: {}
  iq2: {}
  iq3:
    acbandwidth:
    - 0
    bandwidth:
    - 159154943
    - 159154943
    - 159154943
    - 159154943
    quadrature_factor: 0.0
    output_signal: quadrature
    gain: 0.0
    amplitude: 0.0
    phase: 0.0
    output_direct: 'off'
pids:
  pid1: {}
  pid2: {}
  pid3: {}
  pid4: {}
iirs:
  iir: {}
