language: python
  - "2.7"
  - "3.5"
  
before_install:
##- apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

install: 
  - python setup.py install
#  - pip install -r requirements.txt .

before_script: ./autocorrectpep8_script.sh

script: python setup.py test

env:
#- REDPITAYA=192.168.1.100 AUTOCORRECTPEP8=0
- REDPITAYA=localhost AUTOCORRECTPEP8=0
