language: python

install: 
  - pip install flake8 .
  - python setup.py install
#  - pip install -r requirements.txt .

#before_script:
#  - "flake8 --show-source --builtins=_ Teradata"
  
script: python setup.py test

env:
#- REDPITAYA=192.168.1.100
- REDPITAYA=localhost

