language: python

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip
  - sudo pip install --upgrade pip
  - pip install --upgrade pip
  - pip install pep8
  - pip install autopep8
#- apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

install: 
  - python setup.py install
#  - pip install -r requirements.txt .

before_script: ./autocorrectpep8_script.sh

script: python setup.py test

env:
#- REDPITAYA=192.168.1.100 AUTOCORRECTPEP8=0
- REDPITAYA=localhost AUTOCORRECTPEP8=0
