# for setup: must go into travis setup and insert ip address and other data of
# the redpitaya device, and disable concurrent builds to avoid conflicts
# between tests of different python versions

# lots of stuff here comes from https://gist.github.com/dan-blanchard/7045057

# REDPITAYA variables are defined in travis account (encrypted)

notifications:
  email:
    recipients:
      - pyrpl.readthedocs.io@gmail.com
language: generic

env:
  - TRAVIS_PYTHON_VERSION=2.7
  - TRAVIS_PYTHON_VERSION=3.6
  - TRAVIS_PYTHON_VERSION=3.5
  - TRAVIS_PYTHON_VERSION=3.4
os:
  - osx
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo apt-get update;
    fi
  # We do this conditionally because it saves us some downloading.
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
    echo "Invalid combination of OS ($TRAVIS_OS_NAME) and Python version ($TRAVIS_PYTHON_VERSION)";
    fi
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # The next lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  # starts gui support, see https://docs.travis-ci.com/user/gui-and-headless-browsers/
  # and https://github.com/travis-ci/travis-ci/issues/7313#issuecomment-279914149 (for MacOSX)
  - export DISPLAY=":99.0"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    sh -e sudo Xvfb :99 -ac -screen 0 1024x768x8;
    else
    sh -e /etc/init.d/xvfb start;
    fi
  # give it some time to start
  - sleep 3

install:
  # avoid to get cancelled because of very long tests
  # we get issues with building numpy etc if we do not include those in the next line
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy paramiko pandas nose pip pyqt qtpy
  - source activate test-environment
  # overwrite default global config file with a custom one for travis (allows slower communication time)
  - \cp ./travis_global_config.yml ./pyrpl/config/global_config.yml
  - python setup.py install
  # packages for coverage reports
  - conda install --yes -c conda-forge coveralls
  - pip install coverage codecov

# Run test
script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]] || [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]] || [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
    echo "NOSETESTS ARE DISABLED";
    fi
#nosetests;

after_script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]] || [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]] || [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
    codecov;
    fi

# automatic release when a new tag is created needs a few preliminary steps...
# create a Readme.rst for PyPI
# make an executable for linux and upload to sourceforge in python 3.4
before_deploy:
  - echo Deploy
  - source activate test-environment
  - conda install pandoc
  - pandoc --from=markdown --to=rst --output=README.rst README.md
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.4" && "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_TEST_RESULT" == 0 ]]; then
    pip install pyinstaller;
    pyinstaller pyrpl.spec;
    mv dist/pyrpl ./pyrpl-linux;
    python .deploy_to_sourceforge.py pyrpl-linux;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.4" && "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_TEST_RESULT" == 0 ]]; then
    pip install pyinstaller;
    pyinstaller pyrpl.spec;
    mv dist/pyrpl ./pyrpl-osx;
    python .deploy_to_sourceforge.py pyrpl-osx;
    fi

deploy:
  provider: pypi
  user: lneuhaus
  password: $PYPI_PASSWORD
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = 3.4
  distributions: "sdist bdist_wheel --universal"
