env:
#- REDPITAYA_HOSTNAME=192.168.1.100 AUTOCORRECTPEP8=0
- REDPITAYA_HOSTNAME=unavailable REDPITAYA_PASSWORD=root AUTOCORRECTPEP8=0

language: python
  - "2.7"
#  - "3.5"
 
# lots of stuff here comes from https://gist.github.com/dan-blanchard/7045057
notifications:
  email: false
 
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
#before_install:
# - sudo apt-get update
# - sudo apt-get -y install python-pip
# - sudo pip install --upgrade pip
# - sudo pip install pep8
# - sudo pip install autopep8
# - sudo pip install -r requirements.txt .
##- apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
  # Coverage packages are on my binstar channel
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - python setup.py install

#before_script: ./autocorrectpep8_script.sh
  
# Run test
script:
  - nosetests --with-cov --cov pyrpl --cov-config .coveragerc --logging-level=INFO
#script: python setup.py test
#script: python setup.py nosetests

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
