language: python

before_install:
    - pip install pep8

install: 
  - python setup.py install
#  - pip install -r requirements.txt .

#before_script:
#  - find . -name \*.py -exec pep8 --ignore=E402 {} +

script: python setup.py test

env:
#- REDPITAYA=192.168.1.100
- REDPITAYA=localhost

