general:
  # interface module for saving curves (default is pyrpl)
  curvedb: pyrpl
  # level of logging output (can be one in [debug, info, warning, error])
  loglevel: debug
test:
  # maximum reasonable time for a read/write operation
  # time is definitely above 60 ms for travis and arroseur.ddns.net
  max_communication_time: 100.0e-3
